name: Release

on:
  push:
    branches:
      - add-gh-actions

jobs:
  release-app:
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest"
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest"
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-latest"
            args: ""
          - platform: "windows-latest"
            args: ""

    runs-on: ${{ matrix.platform }}
    steps:
      - name: Checkout Project
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}

      - name: Install Linux dependencies
        if: matrix.platform == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf libclang-dev xdg-utils

      - name: Install Node dependencies
        run: npm install

      - name: Generate changelogs
        id: changelog
        run: |
          cargo install git-cliff
          echo 'notes<<EOF' >> $GITHUB_OUTPUT
          git-cliff --latest --strip all --use-branch-tags >> $GITHUB_OUTPUT
          echo 'EOF' >> $GITHUB_OUTPUT

      - name: Build && Publish
        uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          TAURI_SIGNING_PRIVATE_KEY: ${{ secrets.TAURI_SIGNING_PRIVATE_KEY }}
          APPIMAGE_EXTRACT_AND_RUN: 1
        with:
          tagName: __VERSION__
          releaseName: "v__VERSION__"
          releaseBody: "${{ steps.changelog.outputs.notes || '' }}"
          releaseDraft: true
          prerelease: false
          args: ${{ matrix.args }}
